# Generated by Django 5.2.5 on 2025-08-22 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0002_sitesetting_copyright_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='copyright_text',
        ),
    ]
